spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/FullStackMania/CloudConfiguration
          uri: https://github.com/alokebd/cloud-configurations
          search-paths:
           - '{application}'
          refresh-rate: 0
        default-label: main
        
# NOTE: http://localhost:8081/<name>/<profile>/<branch>
# http://localhost:8081/paymentservice/dev/main

server:
  port: 8081
